### ISSUE TITLE
About Us

### ISSUE THREAD

**Issue by kelsey-21** [nss-evening-cohort-10/foundations-group-project-tango-brigade#11]
# Story
As a user, I want to see an about us section us under the title, so I know who these jokers are.

# AC
**WHEN** the about.html loads
**THEN** the about us section shows
**AND** has the content from the google doc

# Dev notes
- group effort to write the about us section

**Comment by isischristopher** [comment]
`<div class= "aboutBio">
<p>The Starjets were a late 1970s power pop/group from Belfast, Northern Ireland. They changed their name to Tango Brigade in the mid-’80s.</p>

<p>Originally formed in Belfast in 1976, the band consisted of guitarist/vocalist Terry Sharpe, guitarist/vocalist Paul Bowen, bassist Sean Martin and drummer Liam L'Estrange. The group sported a mix of punk and mainstream pop influences. Early sets consisted of such 1960s pop standards as "Please Please Me" by The Beatles and "Sugar, Sugar" by The Archies, at a time when such light, happy fare was an anathema to the punk community. The band also stood out from their punk contemporaries with their tight, sophisticated harmonies. Appropriately, they opened for groups as diverse as Teen Idols the Bay City Rollers and aggressive punk rockers Stiff Little Fingers. Because of their clean-cut, boys-next-door image, sugary songs, and amiable persona, they were sometimes even tagged the "Bay City Rollers of punk".</p>

<p>The group secured a major record label recording contract with Epic Records and relocated to London in November 1977. They released a number of singles in 1979, with their only chart hit being "War Stories" b/w "Do the Push", which peaked at No. 51 on the UK Singles Chart. They released one album, 1979's God Bless the Starjets, but it failed commercially. </p>

<p>Following the release of the "Shiraleo" single in March 1980, the band changed its name to Tango Brigade and released one more single, before finally splitting up permanently.
However, due to popular demand, the band is back together and unifying the world with their tasteful melodies and groovy rhythms. </p>
</div>`
